### ISSUE TITLE
Add user defined mod alerts

### ISSUE THREAD

**Issue by cujarrett** [cujarrett/destiny-insights-frontend#4]
## What

Add the ability for a user to set mods they want alerts for.

## Tasks

- [ ] - Add security to ensure we don't alert the wrong Twitter account. Possibly use Twitter OAuth 2 flow to authenticate them.
- [ ] - Add user desired mod alert database, likely DynamoDB. This includes terraform for IaC.
- [ ] - Add Lambda for compute to loop over desired mod alert database and alert those users who marked that days mods for alerts.
  - [ ] - Build check to ensure they follow the bot.
